### ISSUE TITLE
Enable use of .NET Core / Linux / Docker: Getting 'CspKeyContainerInfo' requires Windows Cryptographic API error

### ISSUE THREAD

**Issue by onahirniak** [docusign/docusign-csharp-client#214]
I'm developing **aspnetcore2.2** application and using **DucuSign SDK 3.1.3**
When I invoke `RequestJWTUserToken `method from the VisualStudio(Windows machine) everything is okay, but when I try to invoke the same method from Docker I get the following error:
'CspKeyContainerInfo' requires Windows Cryptographic API (CAPI), which is not available on this platform.

 ```
System.PlatformNotSupportedException : 'CspKeyContainerInfo' requires Windows Cryptographic API (CAPI), which is not available on this platform.
Stack Trace:
   at System.Security.Cryptography.RSACryptoServiceProvider.get_CspKeyContainerInfo()
   at Microsoft.IdentityModel.Tokens.RSACryptoServiceProviderProxy..ctor(RSACryptoServiceProvider rsa) in C:\agent2\_work\56\s\src\Microsoft.IdentityModel.Tokens\RsaCryptoServiceProviderProxy.cs:line 74
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter.Initialize(RSA rsa, String algorithm) in C:\agent2\_work\56\s\src\Microsoft.IdentityModel.Tokens\AsymmetricAdapter.cs:line 305
   at Microsoft.IdentityModel.Tokens.AsymmetricAdapter..ctor(SecurityKey key, String algorithm, HashAlgorithm hashAlgorithm, HashAlgorithmName hashAlgorithmName, Boolean requirePrivateKey) in C:\agent2\_work\56\s\src\Microsoft.IdentityModel.Tokens\AsymmetricAdapter.cs:line 84
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.ResolveAsymmetricAdapter(SecurityKey key, String algorithm, Boolean requirePrivateKey) in C:\agent2\_work\56\s\src\Microsoft.IdentityModel.Tokens\AsymmetricSignatureProvider.cs:line 207
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures) in C:\agent2\_work\56\s\src\Microsoft.IdentityModel.Tokens\AsymmetricSignatureProvider.cs:line 133
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures) in C:\agent2\_work\56\s\src\Microsoft.IdentityModel.Tokens\CryptoProviderFactory.cs:line 442
   at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.CreateEncodedSignature(String input, SigningCredentials signingCredentials) in C:\agent2\_work\56\s\src\Microsoft.IdentityModel.JsonWebTokens\JwtTokenUtilities.cs:line 69
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials) in C:\agent2\_work\56\s\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 504
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor) in C:\agent2\_work\56\s\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 466
   at DocuSign.eSign.Client.ApiClient.RequestJWTUserToken(String clientId, String userId, String oauthBasePath, Byte[] privateKeyBytes, Int32 expiresInHours, List`1 scopes)
```

**Comment by onahirniak** [comment]
Here is a similar issue with `JwtSecurityTokenHandler`:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1038

**Comment by mikesig** [comment]
Also experiencing this problem on my Linux box. Does anyone have an update on this?

**Comment by RajRele** [comment]
Hi All, sorry you guys are facing this issue. I have open an investigation ticket (DCM-3073), will be updating this channel with our progress.

**Comment by onahirniak** [comment]
@RajRele Hey, thank you for investigating the issue. Is there any news?

**Comment by LarryKlugerDS** [comment]
Thank you for raising this issue.

We've added the issue to our roadmap with internal ticket number DCM-3073. Please ask your DocuSign business or support contact to add your information to the ticket.

Unfortunately we don't have a schedule date for the enhancement.

## Workarounds

In the meantime, this [blog post](https://suchprogramming.com/using-capi-within-a-docker-container/) may be of help.

If you're able to get the SDK working by adding additional software to the Docker image, please let us know and we'll add the information to our documentation.

If you can solve the problem through a pull request to the SDK, that would be helpful too.

Another option would be independently implement the JWT Grant flow. DocuSign's server-side implementation of the JWT flow is quite standard and is [documented](https://developers.docusign.com/esign-rest-api/guides/authentication/oauth2-jsonwebtoken).

For example, see [here](https://stackoverflow.com/questions/49834145/how-to-generate-a-jwt-with-net-core) and [here](https://www.scottbrady91.com/C-Sharp).

**Comment by almostdj** [comment]
What is the progress on this issue?
Because, right now we are suffering from this issue. We have to show some demo to end user, and he must decide to buy subscription for DocuSign or not...
Apparently he shouldn't!
Because it's almost a month since this issue started and it's still not resolved.... It's speaks a lot about client support!

**Comment by LarryKlugerDS** [comment]
I'm sorry that this issue is holding up your project.

* Please ask your DocuSign business or technical contacts to add your organization name to the DCM-3073 ticket.

A workaround is to not use the DocuSign-supplied JWT method. Instead use a different library to generate the JWT, then send it to DocuSign to receive back an access token.

For example, this library, https://github.com/jwt-dotnet/jwt may be of help.

This page also has a list of JWT software for C# -- https://jwt.io/ 

Please advise if you're able to use another library.

**Comment by odinnou** [comment]
Hello, we are facing the same issue, we will try to implement this : https://developers.docusign.com/esign-rest-api/guides/authentication/oauth2-jsonwebtoken 

More and more new .NET projects are hosted on Linux, but the development is generally done on Windows.

Hope, I could quickly update your library with this fix

Thanks in advance
Kind regards

**Comment by LarryKlugerDS** [comment]
Hi @odinnou,
I'm not sure if I'm reading your comment correctly, but if you think you could produce a pull request to solve the problem, that would be greatly appreciated.

The bug is on our roadmap to fix, but we don't have a planned schedule yet.

**Comment by odinnou** [comment]
At the moment, we will just implement the work around in our code, and we will paste the code here if you want.

**Comment by LarryKlugerDS** [comment]
Hi, 
If you have a work around, we'd appreciate the example.
Thanks,
Larry

**Comment by odinnou** [comment]
Hello, we think we found a fix today.

We have look at the code and especially the RequestJWTUserToken function (the problem is the same with RequestJWTApplicationToken  but we don't use it)

We have paste this function into our code to detect where the code crash exactly.
The first crash was here  

`var provider = new RSACryptoServiceProvider(cspParameters);`

Here the entire block of code :

```
#if NETSTANDARD2_0
         var provider = new RSACryptoServiceProvider();
#else
            var cspParameters = new CspParameters
            {
                Flags = CspProviderFlags.UseMachineKeyStore,
            };

            var provider = new RSACryptoServiceProvider(cspParameters);
#
```


We are in .NET Core but the NETSTANDARD2_0 IF was not used (disabled)
So for testing we keep only this line : 

`var provider = new RSACryptoServiceProvider();`

After that first fix, the code crash at this line :  

`var token = handler.CreateToken(descriptor);`


So we have try to upgrade the System.IdentityModel.Tokens.Jwt Nuget Package from 5.3.0 to 5.4.0 and it works


Disclaimer : we only replace the RequestJWTUserToken part from the SDK by this fixed function.


We don't know if this "fix" don't cause any trouble at the rest of the SDK.


Thanks in advance
Kind Regards

Rémi D. from Ineat Conseil

**Comment by HulinCedric** [comment]
Hi @LarryKlugerDS ,

I have try the fact to upgrade `Microsoft.IdentityModel.Protocols` & `System.IdentityModel.Tokens.Jwt` packages to the latest version who support `.NETStandard 2.0` on a MacOS system and it's effectively works.

I will do a pull request if you want.

**Comment by LarryKlugerDS** [comment]
Hi @HulinCedric ,
Yes, a pull request would be appreciated.
I will re-raise this issue to our product development group in a meeting this week. I have updated the internal enhancement request too.

**Comment by HulinCedric** [comment]
Hi @LarryKlugerDS,
There is already a pull request here #223

**Comment by LarryKlugerDS** [comment]
Hi @HulinCedric,
Thank you.

**Comment by RajRele** [comment]
@onahirniak, @mikesig  I have Pre-Release version [4.0.1-rc](https://www.nuget.org/packages/DocuSign.eSign.dll/4.0.1-rc) released, you can test the NuGet package and let us know if the issue still exists. 
PR #232

@HulinCedric, @odinnou thanks for your contribution

**Comment by HulinCedric** [comment]
Hi @RajRele,
It works for me.
```csharp
var userToken = docuSignClient.RequestJWTUserToken(
                             settings.ClientId,
                             settings.UserId,
                             settings.OAuthBasePath,
                             settings.PrivateKeyBytes,
                             settings.ExpiresInHours);
```
This use case who throw exception before on a MacOS system, works perfectly with the version [4.0.1-rc](https://www.nuget.org/packages/DocuSign.eSign.dll/4.0.1-rc)
